// Board
export const GET_BOARD = 'GET_BOARD';
export const GET_BOARD_PENDING = 'GET_BOARD_PENDING';
export const GET_BOARD_FULFILLED = 'GET_BOARD_FULFILLED';
export const GET_BOARD_REJECTED = 'GET_BOARD_REJECTED';

export const CREATE_BOARD = 'CREATE_BOARD';
export const CREATE_BOARD_START = 'CREATE_BOARD_START';
export const CREATE_BOARD_CANCEL = 'CREATE_BOARD_CANCEL';
export const CREATE_BOARD_PENDING = 'CREATE_BOARD_PENDING';
export const CREATE_BOARD_FULFILLED = 'CREATE_BOARD_FULFILLED';
export const CREATE_BOARD_REJECTED = 'CREATE_BOARD_REJECTED';

export const UPDATE_BOARD = 'UPDATE_BOARD';
export const UPDATE_BOARD_START = 'UPDATE_BOARD_START';
export const UPDATE_BOARD_CANCEL = 'UPDATE_BOARD_CANCEL';
export const UPDATE_BOARD_PENDING = 'UPDATE_BOARD_PENDING';
export const UPDATE_BOARD_FULFILLED = 'UPDATE_BOARD_FULFILLED';
export const UPDATE_BOARD_REJECTED = 'UPDATE_BOARD_REJECTED';

export const DELETE_BOARD = 'DELETE_BOARD';
export const DELETE_BOARD_PENDING = 'DELETE_BOARD_PENDING';
export const DELETE_BOARD_FULFILLED = 'DELETE_BOARD_FULFILLED';
export const DELETE_BOARD_REJECTED = 'DELETE_BOARD_REJECTED';

export const GET_BOARDS = 'GET_BOARDS';
export const GET_BOARDS_PENDING = 'GET_BOARDS_PENDING';
export const GET_BOARDS_FULFILLED = 'GET_BOARDS_FULFILLED';
export const GET_BOARDS_REJECTED = 'GET_BOARDS_REJECTED';
