// Board
export const GET_BOARD = 'GET_BOARD';
export const GET_BOARD_PENDING = 'GET_BOARD_PENDING';
export const GET_BOARD_FULFILLED = 'GET_BOARD_FULFILLED';
export const GET_BOARD_REJECTED = 'GET_BOARD_REJECTED';

export const CREATE_BOARD = 'CREATE_BOARD';
export const CREATE_BOARD_START = 'CREATE_BOARD_START';
export const CREATE_BOARD_CANCEL = 'CREATE_BOARD_CANCEL';
export const CREATE_BOARD_PENDING = 'CREATE_BOARD_PENDING';
export const CREATE_BOARD_FULFILLED = 'CREATE_BOARD_FULFILLED';
export const CREATE_BOARD_REJECTED = 'CREATE_BOARD_REJECTED';

export const UPDATE_BOARD = 'UPDATE_BOARD';
export const UPDATE_BOARD_START = 'UPDATE_BOARD_START';
export const UPDATE_BOARD_CANCEL = 'UPDATE_BOARD_CANCEL';
export const UPDATE_BOARD_PENDING = 'UPDATE_BOARD_PENDING';
export const UPDATE_BOARD_FULFILLED = 'UPDATE_BOARD_FULFILLED';
export const UPDATE_BOARD_REJECTED = 'UPDATE_BOARD_REJECTED';

export const DELETE_BOARD = 'DELETE_BOARD';
export const DELETE_BOARD_PENDING = 'DELETE_BOARD_PENDING';
export const DELETE_BOARD_FULFILLED = 'DELETE_BOARD_FULFILLED';
export const DELETE_BOARD_REJECTED = 'DELETE_BOARD_REJECTED';

export const GET_BOARDS = 'GET_BOARDS';
export const GET_BOARDS_PENDING = 'GET_BOARDS_PENDING';
export const GET_BOARDS_FULFILLED = 'GET_BOARDS_FULFILLED';
export const GET_BOARDS_REJECTED = 'GET_BOARDS_REJECTED';

// Column
export const GET_COLUMN = 'GET_COLUMN';
export const GET_COLUMN_PENDING = 'GET_COLUMN_PENDING';
export const GET_COLUMN_FULFILLED = 'GET_COLUMN_FULFILLED';
export const GET_COLUMN_REJECTED = 'GET_COLUMN_REJECTED';

export const CREATE_COLUMN = 'CREATE_COLUMN';
export const CREATE_COLUMN_START = 'CREATE_COLUMN_START';
export const CREATE_COLUMN_CANCEL = 'CREATE_COLUMN_CANCEL';
export const CREATE_COLUMN_PENDING = 'CREATE_COLUMN_PENDING';
export const CREATE_COLUMN_FULFILLED = 'CREATE_COLUMN_FULFILLED';
export const CREATE_COLUMN_REJECTED = 'CREATE_COLUMN_REJECTED';

export const UPDATE_COLUMN = 'UPDATE_COLUMN';
export const UPDATE_COLUMN_START = 'UPDATE_COLUMN_START';
export const UPDATE_COLUMN_CANCEL = 'UPDATE_COLUMN_CANCEL';
export const UPDATE_COLUMN_PENDING = 'UPDATE_COLUMN_PENDING';
export const UPDATE_COLUMN_FULFILLED = 'UPDATE_COLUMN_FULFILLED';
export const UPDATE_COLUMN_REJECTED = 'UPDATE_COLUMN_REJECTED';

export const DELETE_COLUMN = 'DELETE_COLUMN';
export const DELETE_COLUMN_PENDING = 'DELETE_COLUMN_PENDING';
export const DELETE_COLUMN_FULFILLED = 'DELETE_COLUMN_FULFILLED';
export const DELETE_COLUMN_REJECTED = 'DELETE_COLUMN_REJECTED';

export const GET_COLUMNS = 'GET_COLUMNS';
export const GET_COLUMNS_PENDING = 'GET_COLUMNS_PENDING';
export const GET_COLUMNS_FULFILLED = 'GET_COLUMNS_FULFILLED';
export const GET_COLUMNS_REJECTED = 'GET_COLUMNS_REJECTED';

// Card
export const GET_CARD = 'GET_CARD';
export const GET_CARD_PENDING = 'GET_CARD_PENDING';
export const GET_CARD_FULFILLED = 'GET_CARD_FULFILLED';
export const GET_CARD_REJECTED = 'GET_CARD_REJECTED';

export const CREATE_CARD = 'CREATE_CARD';
export const CREATE_CARD_START = 'CREATE_CARD_START';
export const CREATE_CARD_CANCEL = 'CREATE_CARD_CANCEL';
export const CREATE_CARD_PENDING = 'CREATE_CARD_PENDING';
export const CREATE_CARD_FULFILLED = 'CREATE_CARD_FULFILLED';
export const CREATE_CARD_REJECTED = 'CREATE_CARD_REJECTED';

export const UPDATE_CARD = 'UPDATE_CARD';
export const UPDATE_CARD_START = 'UPDATE_CARD_START';
export const UPDATE_CARD_CANCEL = 'UPDATE_CARD_CANCEL';
export const UPDATE_CARD_PENDING = 'UPDATE_CARD_PENDING';
export const UPDATE_CARD_FULFILLED = 'UPDATE_CARD_FULFILLED';
export const UPDATE_CARD_REJECTED = 'UPDATE_CARD_REJECTED';

export const DELETE_CARD = 'DELETE_CARD';
export const DELETE_CARD_PENDING = 'DELETE_CARD_PENDING';
export const DELETE_CARD_FULFILLED = 'DELETE_CARD_FULFILLED';
export const DELETE_CARD_REJECTED = 'DELETE_CARD_REJECTED';

export const GET_CARDS = 'GET_CARDS';
export const GET_CARDS_PENDING = 'GET_CARDS_PENDING';
export const GET_CARDS_FULFILLED = 'GET_CARDS_FULFILLED';
export const GET_CARDS_REJECTED = 'GET_CARDS_REJECTED';
